### ISSUE TITLE
MediaMarkt / graphql calls are not accepted any longer

### ISSUE THREAD

**Issue by beyourselfman** [ilox/utility-script#2]
Browser - working

https://www.mediamarkt.de/api/v1/graphql?operationName=GetSelectProduct&variables={"hasMarketplace":true,"id":"2679163"}&extensions={"pwa":{"salesLine":"Media","country":"DE","language":"de","contentful":true},"persistedQuery":{"version":1,"sha256Hash":"ccff035af97223fd0e8f53764944a2ec568b827e754720ab9244ea2aa2e3a1db"}}

Script - not working

https://www.mediamarkt.de/api/v1/graphql?operationName=GetSelectProduct&variables={"hasMarketplace":false,"id":"2671659"}&extensions={"pwa":{"salesLine":"Media","country":"DE","language":"de","contentful":true},"persistedQuery":{"version":1,"sha256Hash":"f5e7004116779965b89fa241c099e63ff76feb2bc5eaa1c747988f0d146f68ba"}}

response

400

{"errors":[{"message":"Cannot query field \"mainFeatures\" on type \"GraphqlProduct\". Did you mean \"manufacturer\"?","locations":[{"line":104,"column":3}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}

Vermutung: SHA-Hash des API-Calls hat sich geändert

**Comment by beyourselfman** [comment]
If the error was caused by the hash value, then the script still uses the old hash value 'f5e7004116779965b89fa241c099e63ff76feb2bc5eaa1c747988f0d146f68ba'

console:
window.ILOX_PRODUCT="TEST";
eval(atob('ZmV0Y2goJ2h0dHBzOi8vdG9vbHMubmVoYWxpc3QuaW8vaWxveC5taW4uanMnKS50aGVuKHIgPT4gci50ZXh0KCkpLnRoZW4ociA9PiBldmFsKHIpKTs='));

script calls:

https://www.mediamarkt.de/api/v1/graphql?operationName=GetSelectProduct&variables={"hasMarketplace":false,"id":"2612576"}&extensions={"pwa":{"salesLine":"Media","country":"DE","language":"de","contentful":true},"persistedQuery":{"version":1,"sha256Hash":"f5e7004116779965b89fa241c099e63ff76feb2bc5eaa1c747988f0d146f68ba"}}

**Comment by beyourselfman** [comment]
![image](https://user-images.githubusercontent.com/16084575/118691633-8de8e900-b809-11eb-9cd8-9068d98daf89.png)

**Comment by nehalist** [comment]
Could you please try a different browser? Could be a caching issue. If so I probably have to adjust the calling script.

**Comment by beyourselfman** [comment]
It's working now - probably a cache problem on my side :-)

![image](https://user-images.githubusercontent.com/16084575/118692240-1d8e9780-b80a-11eb-80f6-b26eebe1ec99.png)

**Comment by nehalist** [comment]
Thanks for letting me - I'll attach a timestamp to the request nevertheless with the next upate.
